platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'DebugDev' => :debug,
  'DebugUat' => :debug,
  'DebugDemo' => :debug,
  'DebugProd' => :debug,
  'Profile' => :release,
  'ProfileDev' => :release,
  'ProfileUat' => :release,
  'ProfileDemo' => :release,
  'ProfileProd' => :release,
  'Release' => :release,
  'ReleaseDev' => :release,
  'ReleaseUat' => :release,
  'ReleaseDemo' => :release,
  'ReleaseProd' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  # Fix for resource fork / xattr codesign issue on M-series Macs
  system("find #{installer.sandbox.root} -exec xattr -cr {} \\; 2>/dev/null")
end